### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by yukkysaito** [libornovax/master_thesis_code#43]
I want to know how to build and requirements.
In my environment, I can build original caffe.
(https://github.com/BVLC/caffe)

my environment :
GPU: GTX 1080
CUDA : version 8.0
cuDNN : v6

**Comment by yukkysaito** [comment]
I run following command
$ cp Makefile.config.example Makefile.config
$ mkdir build
$ cd build
$ cmake ..
$ make
output :
```
...
/home/hogehoge/workspace/master_thesis_code/caffe/include/caffe/util/cudnn.hpp:113:70: error: too few arguments to function ‘cudnnStatus_t cudnnSetConvolution2dDescriptor(cudnnConvolutionDescriptor_t, int, int, int, int, int, int, cudnnConvolutionMode_t, cudnnDataType_t)’
       pad_h, pad_w, stride_h, stride_w, 1, 1, CUDNN_CROSS_CORRELATION));
```

**Comment by libornovax** [comment]
Try linking with cuDNN 5.3. The project uses > 1 year old distribution of Caffe. cuDNN 6.0 does not work for me either.

**Comment by yukkysaito** [comment]
Thank you. I try it.
I reply later :+1:

**Comment by Markusgami** [comment]
I found a better solution to this..
You can still using cuDNN 6.0 to build.
What you need to do is to edit cudnn.hpp to call the right version of function.
For example , the function which caused your problem is cudnnSetConvolution2dDescriptor() .. 
Just add suffix _v4 to the function name..... as "cudnnSetConvolution2dDescriptor_v4()"  then It will work.
Hope this helps

**Comment by libornovax** [comment]
@Markusgami thank you for your comment. In deed that might be a solution, however I do not see it as very good practice to alter the source code of the library - this might break other code where you are using cuDNN.
