### ISSUE TITLE
Inference times

### ISSUE THREAD

**Issue by suvam-bag** [libornovax/master_thesis_code#54]
Hello @libornovax, 
Thank you for your great work on an end to end pipeline for 3D object detection. I was wondering if you have any benchmarking numbers for inference time from your experiments. This is what I got - 
1. x86-64 PC with 12GB GTX 1080, 32GB RAM - average 115 ms for 1242x375 image.
2. Nvidia Jetson TX2 - average 2.1 sec for 1242x375 image.

**Comment by libornovax** [comment]
Hi, as far as I remember I was running the inference on GeForce GTX Titan X (12GB) in about 10fps. That is around 100 ms / image on the KITTI images (1242x375). So your number (1) would agree since it can of course vary depending on the data read speed and how many boxes on the output you are reconstructing.

**Comment by jeannotes** [comment]
@suvam-bag @libornovax I tried, about 50ms, using 2080ti.
