### ISSUE TITLE
Is there an implementation in Tensorflow?

### ISSUE THREAD

**Issue by jkstyle2** [libornovax/master_thesis_code#55]
Thanks for sharing your awesome work!
As title says, I wonder if there's an implementation written in tensorflow
Thanks

**Comment by libornovax** [comment]
Hi, unfortunately yes and no. I wrote one during a project at the university after my Master's, however it was paid by a private company so I could not release it. Anyway, sorry!

**Comment by jkstyle2** [comment]
@libornovax  Ah.. that's very sad to hear that for me. 
I am only an entry-level student in AI and I've been wandering around to find a great reference to learn from. Your materials have got all I really need to easily follow up with nice codes and well-written thesis paper.
I'm also very new to programming, just starting with tensorflow framework, and I don't think I can learn programming in a new framework at the moment.. 
Sir, then is there any other reference you could recommend? I would very very appreciate it!!

**Comment by libornovax** [comment]
Hi, thanks for the compliments!

Regarding the recommendations, I very much like the online book from Michael Nielsen [http://neuralnetworksanddeeplearning.com](http://neuralnetworksanddeeplearning.com), which guides very nicely through basics and some advanced techniques in neural networks and also gives nice examples! If you want directly basics on which my thesis builds, probably the best to start with is the paper *Long, Jonathan, Evan Shelhamer, and Trevor Darrell. "Fully convolutional networks for semantic segmentation."*

As for the framework, I would probably not choose Tensorflow to start with as it might be a bit harder to grasp, but that depends on your programming skills ;) The easiest framework from my POV is PyTorch, which kind of works in the intuitive way (compared to Tensorflow, where building the graph and running the computation in some session might sound a bit scary). Both are in Python, which simplifies a lot of things like quick try/debug iterations and data manipulation etc.

That said, for my Master thesis I chose Caffe because there it forces you to program backpropagation for your custom layers on your own, which means you can learn a lot. Also C++ was probably the language I was the most familiar with.

I hope you have fun!
