### ISSUE TITLE
An old mistake about inverse projection

### ISSUE THREAD

**Issue by JiangStein** [libornovax/master_thesis_code#59]
I start a new issue, for I am not sure whether a having closed issue can be seen...

Sorry for bothering you again after such a long time...I didn't try to solve this problem half a year ago because I only need to use the ground plane of the bounding box at that time, and it looks good enough.

I am now working for another project, and I hope to use your method again, but I still cannot solve that...

When I applied Intrinsic parameters(K) of my camera as P, I got the result in the picture above. but when p1~p3 is the KR part and p4 is -KRC, It doesn't work...

I am puzzled about where should be the origin of world coordinates. Since I have restored the point cloud of the environment by using ORB-SLAM, I simply set the position of car in the first frame as the origin of world coordinates, and have successfully restored the overhead map of the environment, so I think there is nothing wrong with the camera position C and rotation matrix R.

![1778153134](https://user-images.githubusercontent.com/35327591/50287255-0ca49500-049d-11e9-8c8a-1bd711870c84.png)
Here is an example of how I get K,C and R. The top-left one is the origin of camera matrix, the bottom-right one is the origin of world coordinate, where x is red, y is green, z is blue.

The size of my picture is 640x360 and I didn't resize it. the line from the PGP file is

```
/home/stein/dataset/parkingSlot/zed_0516_1700/resized/000000.png 
346.6559 0.000000 298.8324 0.000000 
0.000000 346.2212 186.4451 0.000000 
0.000000 0.000000 1.000000 0.000000 
0.000000 0.891600 0.452900 -1.52000
```
Through which I got the result shown in picture half a year ago:
![40293960-ec46ae7c-5d05-11e8-8753-4cc1852ca2d0](https://user-images.githubusercontent.com/35327591/50287342-69a04b00-049d-11e9-84c1-c9a8a2b3c95a.png)

The matrix K is
```
346.6559 0.000000 298.8324
0.000000 346.2212 186.4451
0.000000 0.000000 1.000000
```

The rotation matrix R from camera coordinates to world coordinates of this frame is
```
-1 0 0
0 0.4529 -0.8916
0 -0.8916 -0.4529
```
and I think the rotation matrix from world coordinates to camera coordinates is also R.

The camera position in world coordinates (matrix C) is
```
1 
-0.6 
1.52
```
However, after calculation by using P=KR[I|-C], I got the result matrix P:
```
-346.6  -266.4  -135.3  392.5
     0      -9.43   -393.1 -591.9
     0   -0.8916 -0.4526 0.152
```
and it doesn't work.

I think the mistake I made might be:
1.I should crop the picture into KITTI size(1242x375) first.
2.I misunderstood K,R or C.
3.The unit of numbers is not the same(millimeter for matrix K, and meter for matrix R,C, ground plane.

Could you tell me what I did wrong?

Sincerely hoping for your reply.

**Comment by libornovax** [comment]
Hi, sorry that I took so much time to answer you question. I tried to create the P matrix from the K, R and C you mention and from my computations your `P[1,3]` should be a positive number (+591.9) and in your P matrix above it's negative. Can you check if it works if you change it?

What I did:
```
K = np.matrix([
    [346.6559, 0.000000, 298.8324],
    [0.000000, 346.2212, 186.4451],
    [0.000000, 0.000000, 1.000000]
])
R = np.matrix([
    [-1, 0, 0],
    [0, 0.4529, -0.8916],
    [0, -0.8916, -0.4529]
])
C = np.matrix([
    [1],
    [-0.6],
    [1.52]
])

print(K * R)
# matrix([[-346.6559    , -266.43896784, -135.34119396],
#         [   0.        ,   -9.43086968, -393.13180771],
#         [   0.        ,   -0.8916    ,   -0.4529    ]])

print(-K * R * C)
# matrix([[  3.92511134e+02],
#         [  5.91901826e+02],
#         [  1.53448000e-01]])
```

**Comment by JiangStein** [comment]
Thanks a lot for helping me! Sorry I'm busy preparing for an exam last week so I didn't reply to you on time.
I've tried your result, but it still doesn't work...

I'm now puzzled about where the origin of world coordinate is. Is it a fixed point in your method?

I get the above result by set R as I, and set C as zero, which means that the camera is located in the origin of world, and the camera coordinate and the ground coordinate is the same.  But if it works, it is not necessary to calculate P. I guess I misunderstand some important things.
Another question is that I got the same result by setting d in ground plane as 1.6 and 1600. Should it affects the result?

Could you help me test whether it works on your computer? I attached some images that get wrong answer. 

Thanks a lot!
[Samples.tar.gz](https://github.com/libornovax/master_thesis_code/files/2777841/Samples.tar.gz)

**Comment by libornovax** [comment]
Hi, sorry for not writing for so long. I had a more detailed look on what is happening and tried running the inference on your images.

I think I found the problem - the thing is that your camera and the camera in the KITTI dataset have a very different pitch (your is looking more to the ground). Since the net is trained on the KITTI images it learns how to place the corners of the boxes for the viewpoint of the KITTI camera. In your case the close cars are in a very different orientation w.r.t. the camera and the net predicts the corners of the box wrongly for them. You can see that below:
![figure_1](https://user-images.githubusercontent.com/19144779/52672316-cf4d0880-2f1d-11e9-9915-6440ae5cfa65.png)
![figure_2](https://user-images.githubusercontent.com/19144779/52672393-06bbb500-2f1e-11e9-92d1-17fc28f1e44f.png)
(I ran the inference without providing the PGP file, which leaves out the optimization of the box to a square)

So as you can see the cars in the distance have the corners predicted quite well (the viewpoint is similar to KITTI), whereas the close cars have the rear corners completely wrong. This then directly translates to a wrong 3D bounding box.

How you can solve this is to for example fine-tune the network on your dataset, which should correct for these problems!

About the origin and so on. It does not really matter where you put the origin of the 3D coordinate system since the 3D coordinates are computed by back-projecting from the image. It would matter if you had your labels in 3D in some coordinate system - then you would of course have to use that one.

And yes, the result is "the same" regardless of whether you set d to 1.6 or 1600. This is because the back-projection has one degree of freedom (since without knowing some object in the scene one cannot tell what is the scale of the scene - as far as the camera is concerned it is the same whether the car is 1.6m high or 1.6cm high). By setting (in this case) the d in the ground plane you define the scale of your scene.

I hope this helps!

**Comment by JiangStein** [comment]
Thank you. I think you are right. I didn't consider about pitch before. It seems that I have to fine-tune the network. 
Thank you again for helping me again and again, you really helped me a lot.
Best wish!
